<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "idurl2speakingurl"
 *
 * Auto generated by Extension Builder 2015-06-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Convert id URLs to Speaking URLs',
	'description' => 'Converts URLs with ?id= to speaking URLs, can be used to generate rewrites after activating RealURL',
	'category' => 'module',
	'author' => 'Lorenz',
	'author_email' => 'lorenz.ulrich@visol.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.99.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);